CREATE TABLE MOVIE (
	ID INTEGER UNIQUE NOT NULL,
	TITLE VARCHAR(20),
	AGE_RATING INTEGER,
	RATING INTEGER
);

INSERT INTO  MOVIE VALUES (1, 'Piratas do Caribe', 18, 8);
INSERT INTO  MOVIE VALUES (2, 'Harry Potter', 14, 9);

SELECT TITLE FROM MOVIE;
SELECT LOCATION FROM CINEMA;

DROP TABLE CINEMA;
DROP TABLE MOVIE;